const artImages = [
    {
        full:"/build/images/art/arm.jpg",
        thumb:"/build/images/art/thumbs/arm.jpg"
    },
    {
        full:"/build/images/art/animation.jpg",
        thumb:"/build/images/art/thumbs/animation.jpg"
    },
    {
        full:"/build/images/art/collage1.jpg",
        thumb:"/build/images/art/thumbs/collage1.jpg"
    },
    {
        full:"/build/images/art/collage2.jpg",
        thumb:"/build/images/art/thumbs/collage2.jpg"
    },
    {
        full:"/build/images/art/collage3.jpg",
        thumb:"/build/images/art/thumbs/collage3.jpg"
    },
    {
        full:"/build/images/art/figure1.jpg",
        thumb:"/build/images/art/thumbs/figure1.jpg"
    },
    {
        full:"/build/images/art/figure2.jpg",
        thumb:"/build/images/art/thumbs/figure2.jpg"
    },
    {
        full:"/build/images/art/figure3.jpg",
        thumb:"/build/images/art/thumbs/figure3.jpg"
    },
    {
        full:"/build/images/art/figure4.jpg",
        thumb:"/build/images/art/thumbs/figure4.jpg"
    },
    {
        full:"/build/images/art/head.jpg",
        thumb:"/build/images/art/thumbs/head.jpg"
    },
    {
        full:"/build/images/art/shining.jpg",
        thumb:"/build/images/art/thumbs/shining.jpg"
    },
    {
        full:"/build/images/art/star_wars.jpg",
        thumb:"/build/images/art/thumbs/star_wars.jpg"
    }
]

export default artImages;
