const designImages = [
    // ROW 1
    {
        full:"/build/images/design/soquaint-logo-collage.jpg",
        thumb:"/build/images/design/thumbs/soquaint-logo-collage.jpg"
    },
    {
        full:"/build/images/design/abc-shs-h.jpg",
        thumb:"/build/images/design/thumbs/abc-shs-h.jpg"
    },
    {
        full:"/build/images/design/business-card-1.jpg",
        thumb:"/build/images/design/thumbs/business-card-1.jpg"
    },
    {
        full:"/build/images/design/business-card-2.jpg",
        thumb:"/build/images/design/thumbs/business-card-2.jpg"
    },
    {
        full:"/build/images/design/FirstTimeServiceSpecialsCard-1.jpg",
        thumb:"/build/images/design/thumbs/FirstTimeServiceSpecialsCard-1.jpg"
    },
    {
        full:"/build/images/design/FirstTimeServiceSpecialsCard-2.jpg",
        thumb:"/build/images/design/thumbs/FirstTimeServiceSpecialsCard-2.jpg"
    },
    {
        full:"/build/images/design/food-characters.jpg",
        thumb:"/build/images/design/thumbs/food-characters.jpg"
    },
    {
        full:"/build/images/design/gabby-logo.jpg",
        thumb:"/build/images/design/thumbs/gabby-logo.jpg"
    },
    {
        full:"/build/images/design/jungle-babe.jpg",
        thumb:"/build/images/design/thumbs/jungle-babe.jpg"
    },
    {
        full:"/build/images/design/soquaint-house.jpg",
        thumb:"/build/images/design/thumbs/soquaint-house.jpg"
    },
    {
        full:"/build/images/design/styling-tips.jpg",
        thumb:"/build/images/design/thumbs/styling-tips.jpg"
    },
    {
        full:"/build/images/design/more-styling-tips.jpg",
        thumb:"/build/images/design/thumbs/more-styling-tips.jpg"
    },
    {
        full:"/build/images/design/photo-tips.jpg",
        thumb:"/build/images/design/thumbs/photo-tips.jpg"
    },
    {
        full:"/build/images/design/keep-on-keeping-on-kc.jpg",
        thumb:"/build/images/design/thumbs/keep-on-keeping-on-kc.jpg"
    },
    {
        full:"/build/images/design/kdot.jpg",
        thumb:"/build/images/design/thumbs/kdot.jpg"
    },
    {
        full:"/build/images/design/cat-tshirt.jpg",
        thumb:"/build/images/design/thumbs/cat-tshirt.jpg"
    },
    // ROW 2
    {
        full:"/build/images/design/Studio-324-Color-Logos.jpg",
        thumb:"/build/images/design/thumbs/Studio-324-Color-Logos.jpg"
    },
    {
        full:"/build/images/design/STUDIO-324-HEXAGON-LOGO-black.jpg",
        thumb:"/build/images/design/thumbs/STUDIO-324-HEXAGON-LOGO-black.jpg"
    },
    {
        full:"/build/images/design/STUDIO-324-HEXAGON-LOGO-yellow-white.jpg",
        thumb:"/build/images/design/thumbs/STUDIO-324-HEXAGON-LOGO-yellow-white.jpg"
    },
    {
        full:"/build/images/design/ombre-jacket-babe.jpg",
        thumb:"/build/images/design/thumbs/ombre-jacket-babe.jpg"
    },
    {
        full:"/build/images/design/back2body-gifcard1.jpg",
        thumb:"/build/images/design/thumbs/back2body-gifcard1.jpg"
    },
    {
        full:"/build/images/design/back2body-gifcard2.jpg",
        thumb:"/build/images/design/thumbs/back2body-gifcard2.jpg"
    },
    {
        full:"/build/images/design/B2B-FACE+SKIN MENU_3.jpg",
        thumb:"/build/images/design/thumbs/B2B-FACE+SKIN MENU_3.jpg"
    },
    {
        full:"/build/images/design/B2B-FACE+SKIN MENU_32.jpg",
        thumb:"/build/images/design/thumbs/B2B-FACE+SKIN MENU_32.jpg"
    },
    {
        full:"/build/images/design/lurk.jpg",
        thumb:"/build/images/design/thumbs/lurk.jpg"
    },
    {
        full:"/build/images/design/pineapples-tshirt.jpg",
        thumb:"/build/images/design/thumbs/pineapples-tshirt.jpg"
    },
    {
        full:"/build/images/design/pineapple-tshirt-layout.jpg",
        thumb:"/build/images/design/thumbs/pineapple-tshirt-layout.jpg"
    },
    {
        full:"/build/images/design/baenanacolor.jpg",
        thumb:"/build/images/design/thumbs/baenanacolor.jpg"
    },
    {
        full:"/build/images/design/cat.jpg",
        thumb:"/build/images/design/thumbs/cat.jpg"
    },
    {
        full:"/build/images/design/cone.jpg",
        thumb:"/build/images/design/thumbs/cone.jpg"
    },
    {
        full:"/build/images/design/hugo.jpg",
        thumb:"/build/images/design/thumbs/hugo.jpg"
    },
    // ROW 3
    {
        full:"/build/images/design/soquaint-logo-2.jpg",
        thumb:"/build/images/design/thumbs/soquaint-logo-2.jpg"
    },
    {
        full:"/build/images/design/sonic-50c-corndogs.jpg",
        thumb:"/build/images/design/thumbs/sonic-50c-corndogs.jpg"
    },
    {
        full:"/build/images/design/west-18th-sponsors.jpg",
        thumb:"/build/images/design/thumbs/west-18th-sponsors.jpg"
    },
    {
        full:"/build/images/design/waynea-palooza-logo.jpg",
        thumb:"/build/images/design/thumbs/waynea-palooza-logo.jpg"
    },
    {
        full:"/build/images/design/shoe-photo-guide.jpg",
        thumb:"/build/images/design/thumbs/shoe-photo-guide.jpg"
    },
    {
        full:"/build/images/design/feelings.jpg",
        thumb:"/build/images/design/thumbs/feelings.jpg"
    },
    {
        full:"/build/images/design/all-tshirts.jpg",
        thumb:"/build/images/design/thumbs/all-tshirts.jpg"
    },
    {
        full:"/build/images/design/hands.jpg",
        thumb:"/build/images/design/thumbs/hands.jpg"
    },
    {
        full:"/build/images/design/house_party.jpg",
        thumb:"/build/images/design/thumbs/house_party.jpg"
    },
    {
        full:"/build/images/design/midwestzombie_hands.jpg",
        thumb:"/build/images/design/thumbs/midwestzombie_hands.jpg"
    },
    {
        full:"/build/images/design/pineapplecolor.jpg",
        thumb:"/build/images/design/thumbs/pineapplecolor.jpg"
    },
    {
        full:"/build/images/design/recycling-project.jpg",
        thumb:"/build/images/design/thumbs/recycling-project.jpg"
    },
    {
        full:"/build/images/design/EX_TEARS.jpg",
        thumb:"/build/images/design/thumbs/EX_TEARS.jpg"
    },
    {
        full:"/build/images/design/cat-tshirt-layout.jpg",
        thumb:"/build/images/design/thumbs/cat-tshirt-layout.jpg"
    }
]

export default designImages;
