const photoImages = [
    {
        full:"/build/images/photo/backpack1.jpg",
        thumb:"/build/images/photo/thumbs/backpack1.jpg"
    },
    { 
        full:"/build/images/photo/blackbelt1.jpg",
        thumb:"/build/images/photo/thumbs/blackbelt1.jpg"
    },
    {
        full:"/build/images/photo/blue-wool-hat.jpg",
        thumb:"/build/images/photo/thumbs/blue-wool-hat.jpg"
    },
    {
        full:"/build/images/photo/boots.jpg",
        thumb:"/build/images/photo/thumbs/boots.jpg"
    },
    {
        full:"/build/images/photo/chair.jpg",
        thumb:"/build/images/photo/thumbs/chair.jpg"
    },
    {
        full:"/build/images/photo/beads.jpg",
        thumb:"/build/images/photo/thumbs/beads.jpg"
    },
    {
        full:"/build/images/photo/denimbag1.jpg",
        thumb:"/build/images/photo/thumbs/denimbag1.jpg"
    },
    {
        full:"/build/images/photo/lionbelt1.jpg",
        thumb:"/build/images/photo/thumbs/lionbelt1.jpg"
    },
    {
        full:"/build/images/photo/et.jpg",
        thumb:"/build/images/photo/thumbs/et.jpg"
    },
    {
        full:"/build/images/photo/gold-box.jpg",
        thumb:"/build/images/photo/thumbs/gold-box.jpg"
    },
    {
        full:"/build/images/photo/gray-heels.jpg",
        thumb:"/build/images/photo/thumbs/gray-heels.jpg"
    },
    {
        full:"/build/images/photo/lemons.jpg",
        thumb:"/build/images/photo/thumbs/lemons.jpg"
    },
    {
        full:"/build/images/photo/painting.jpg",
        thumb:"/build/images/photo/thumbs/painting.jpg"
    },
    {
        full:"/build/images/photo/painting-2.jpg",
        thumb:"/build/images/photo/thumbs/painting-2.jpg"
    },
    {
        full:"/build/images/photo/PBR-hat.jpg",
        thumb:"/build/images/photo/thumbs/PBR-hat.jpg"
    },
    {
        full:"/build/images/photo/pillow-sham.jpg",
        thumb:"/build/images/photo/thumbs/pillow-sham.jpg"
    },
    {
        full:"/build/images/photo/purple-hat.jpg",
        thumb:"/build/images/photo/thumbs/purple-hat.jpg"
    },
    {
        full:"/build/images/photo/red-shorts.jpg",
        thumb:"/build/images/photo/thumbs/red-shorts.jpg"
    },
    {
        full:"/build/images/photo/red-tool-kit.jpg",
        thumb:"/build/images/photo/thumbs/red-tool-kit.jpg"
    },
    {
        full:"/build/images/photo/sandals.jpg",
        thumb:"/build/images/photo/thumbs/sandals.jpg"
    },
    {
        full:"/build/images/photo/tele.jpg",
        thumb:"/build/images/photo/thumbs/tele.jpg"
    },
    {
        full:"/build/images/photo/velvet-floral-hat.jpg",
        thumb:"/build/images/photo/thumbs/velvet-floral-hat.jpg"
    },
    {
        full:"/build/images/photo/vtg-camera.jpg",
        thumb:"/build/images/photo/thumbs/vtg-camera.jpg"
    }
]

export default photoImages;